- name: Configure firewall
  command: echo 'install nginx'
  notify:
    - restart firewalld
  tags:
    - always
    - configure

- debug:
    msg: Second task

- name: copy template to server
  template:
    src: dika.txt.j2
    dest: ~/dika.txt
  tags:
    - never
    - configure
